import Link from "next/link";
import { companies, getReviews } from "./lib/data";

export default async function Home({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = (await searchParams).q?.toLowerCase().trim() || "";
  const filtered = companies.filter((company) => !query || `${company.name} ${company.category} ${company.location}`.toLowerCase().includes(query));
  return <main>
    <section className="hero"><div><div className="eyebrow">La réputation, avec des preuves</div><h1>Les avis qui donnent envie d’avancer.</h1><p className="lede">Vixvods rassemble des retours authentiques et les rend lisibles grâce à une analyse transparente. Découvrez avant de choisir.</p><form className="searchbar"><input className="input" name="q" defaultValue={query} placeholder="Rechercher une entreprise, un secteur…" aria-label="Rechercher une entreprise"/><button className="button" type="submit">Explorer</button></form></div><div className="hero-card"><div className="eyebrow">Trust Score</div><div className="score" style={{fontSize: "76px", margin: "22px 0 4px"}}>94<span style={{fontSize: "28px"}}>/100</span></div><p className="muted">Un signal simple, expliqué par les notes, la qualité des retours et les preuves déclarées.</p><div className="notice">Analyse IA + fallback local. Aucune note n’est modifiée automatiquement.</div></div></section>
    <section className="section"><div className="section-head"><div><div className="eyebrow">Explorer</div><h2>Des entreprises à découvrir</h2></div><span className="muted">{filtered.length} résultat{filtered.length > 1 ? "s" : ""}</span></div><div className="grid">{filtered.map((company) => { const reviews = getReviews(company.slug); const avg = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0; return <Link href={`/company/${company.slug}`} className="card company-card" key={company.slug}><div className="company-top"><span className="pill">{company.category}</span><span className="muted">{company.location}</span></div><div><h3>{company.name}</h3><p className="muted">{company.description}</p></div><div className="score-row"><span className="stars">{"★".repeat(Math.round(avg))}{"☆".repeat(5 - Math.round(avg))}</span><span className="muted">{reviews.length} avis</span></div></Link>})}</div>{filtered.length === 0 && <div className="card"><p>Aucune entreprise ne correspond à votre recherche.</p></div>}</section>
    <section className="section grid"><div className="card"><div className="eyebrow">Pour les utilisateurs</div><h2>Choisissez avec plus de contexte.</h2><p className="muted">Lisez les points forts, les nuances et les réponses des entreprises au même endroit.</p></div><div className="card"><div className="eyebrow">Pour les équipes</div><h2>Transformez les retours en progrès.</h2><p className="muted">Centralisez vos avis via l’API privée et répondez avec des brouillons assistés par IA.</p><Link href="/dashboard" className="text-link">Ouvrir l’espace Pro →</Link></div></section>
  </main>;
}
