import Image from "next/image";
import Link from "next/link";
import { companies, getReviews } from "./lib/data";
import Reveal from "./components/Reveal";

export default async function Home({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = (await searchParams).q?.toLowerCase().trim() || "";
  const filtered = companies.filter((company) => !query || `${company.name} ${company.category} ${company.location}`.toLowerCase().includes(query));
  return <main className="home-main">
    <section className="official-hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> La nouvelle couche de confiance</div><h1>Les avis.<br /><em>En clair.</em></h1><p className="lede">Vixvods transforme les retours clients en signaux que tout le monde peut comprendre — sans bruit, sans faux-semblants.</p><div className="hero-actions"><Link href="#explorer" className="button">Explorer les profils <span>↘</span></Link><Link href="/dashboard" className="button button-secondary">Pour les équipes</Link></div><div className="hero-proof"><span className="avatar-stack"><i>J</i><i>M</i><i>A</i><i>+</i></span><span>Rejoignez les premières équipes qui construisent avec les retours.</span></div></div><div className="hero-art"><Image src="/vixvods-hero.jpg" alt="Architecture lumineuse abstraite représentant le flux de confiance Vixvods" fill priority sizes="(max-width: 760px) 100vw, 52vw" className="hero-image" /><div className="art-overlay" /><div className="floating-score"><span>TRUST SCORE</span><strong>94</strong><small>/100</small><div className="mini-line"><i /></div></div><div className="art-caption">SIGNAL / 001<br /><b>Clarté over bruit</b></div></div></section>
    <div className="ticker" aria-label="Principes Vixvods"><div>AVIS AUTHENTIQUES <span>✦</span> ANALYSE EXPLICABLE <span>✦</span> RÉPUTATION EN MOUVEMENT <span>✦</span> AVIS AUTHENTIQUES <span>✦</span> ANALYSE EXPLICABLE <span>✦</span></div></div>
    <Reveal><section className="intro-section"><div><div className="eyebrow">Pourquoi Vixvods</div><h2>Un meilleur signal<br /><span>pour chaque décision.</span></h2></div><div className="intro-text"><p>Les plateformes d’avis accumulent des étoiles. Vixvods ajoute ce qui manque : le contexte, la preuve et une lecture intelligente de chaque expérience.</p><Link href="/faq" className="text-link">Comprendre notre méthode <span>↗</span></Link></div></section></Reveal>
    <Reveal><section className="principles"><article><span className="number">01</span><h3>Lire entre les lignes</h3><p>Une analyse IA courte, compréhensible et toujours distinguée du texte original.</p></article><article><span className="number">02</span><h3>Mesurer avec nuance</h3><p>Le Trust Score est un indicateur transparent, pas un verdict opaque.</p></article><article><span className="number">03</span><h3>Répondre avec justesse</h3><p>Les équipes reçoivent des brouillons utiles pour transformer un retour en action.</p></article></section></Reveal>
    <Reveal><section id="explorer" className="section explorer-section"><div className="section-head"><div><div className="eyebrow">Explorer la confiance</div><h2>Des profils qui parlent vrai.</h2></div><span className="muted">{filtered.length} entreprises</span></div><form className="searchbar searchbar-wide"><span>⌕</span><input className="input" name="q" defaultValue={query} placeholder="Rechercher un nom, un secteur ou une ville…" aria-label="Rechercher" /><button className="button button-small" type="submit">Rechercher</button></form><div className="company-grid">{filtered.map((company, index) => { const reviews = getReviews(company.slug); const avg = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0; return <Link href={`/company/${company.slug}`} className="company-card-new" key={company.slug}><div className={`company-gradient gradient-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><b>{company.name.slice(0, 1)}</b></div><div className="company-content"><div className="company-top"><span className="pill">{company.category}</span><span className="muted">{company.location}</span></div><h3>{company.name}</h3><p className="muted">{company.description}</p><div className="score-row"><span className="stars">{"★".repeat(Math.round(avg))}{"☆".repeat(5 - Math.round(avg))}</span><span className="muted">{reviews.length} avis <b className="arrow">↗</b></span></div></div></Link> })}</div></section></Reveal>
    <Reveal><section className="statement"><div className="eyebrow">Pour les équipes ambitieuses</div><h2>La confiance n’est pas une métrique.<br /><em>C’est une conversation.</em></h2><Link href="/dashboard" className="button">Entrer dans l’espace Pro <span>↗</span></Link></section></Reveal>
  </main>;
}
